import React, { useState } from 'react';
import { X, Printer, Download, Copy, Check, FileText, ShieldAlert } from 'lucide-react';
import { MockCase, ComplianceReferral } from '../../types';
import { RiskBadge } from './RiskBadge';
import { RiskExplanationBox } from './RiskExplanationBox';

interface ReportModalProps {
  caseData: MockCase;
  referral?: ComplianceReferral | null;
  onClose: () => void;
}

export const ReportModal: React.FC<ReportModalProps> = ({
  caseData,
  referral,
  onClose
}) => {
  const [copied, setCopied] = useState(false);

  const reportReference = referral?.referenceNumber || `TG-REP-${caseData.id}`;
  const reportDate = referral?.timestamp || new Date().toISOString().replace('T', ' ').substring(0, 19) + ' UTC';

  const handleCopyJson = () => {
    const payload = JSON.stringify({
      reportReference,
      generatedAt: reportDate,
      caseDetails: caseData,
      referralDetails: referral
    }, null, 2);

    navigator.clipboard.writeText(payload);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  const handleDownloadReport = () => {
    const textReport = `================================================================================
TRACEGUARD CRYPTO FRAUD INTELLIGENCE REPORT [DEMO ONLY]
================================================================================
Reference ID:     ${reportReference}
Generated At:     ${reportDate}
Classification:   SIMULATED FORENSIC TELEMETRY - NON-VERIFIED
Case Identifier:  ${caseData.id} - ${caseData.title}
Blockchain:       ${caseData.blockchain}
Severity Level:   ${caseData.severity} (Score: ${caseData.riskScore}/100)
Primary Target:   ${caseData.seedDetails.address}
Attributed CEX:   ${caseData.attribution.exchange} (Confidence: ${caseData.attribution.confidence}%)
Traced Funds:     $${caseData.suspiciousAmount.toLocaleString()} USD
--------------------------------------------------------------------------------

1. EXECUTIVE SUMMARY
--------------------------------------------------------------------------------
Investigation initiated via ${caseData.source}. Traced illicit flow through ${caseData.nodes.length} nodes 
and ${caseData.edges.length} hops. Identified peel chains, obfuscation mechanisms, and eventual deposit 
into ${caseData.attribution.exchange}.

2. RISK HEURISTICS BREAKDOWN
--------------------------------------------------------------------------------
- Transaction Behavior:  ${caseData.riskComponents['Transaction Behavior']}/100
- Mixer Exposure:        ${caseData.riskComponents['Mixer Exposure']}/100
- Bridge Exposure:       ${caseData.riskComponents['Bridge Exposure']}/100
- Address Clustering:    ${caseData.riskComponents['Address Clustering']}/100
- Velocity Score:        ${caseData.riskComponents['Velocity']}/100
- Exchange Proximity:    ${caseData.riskComponents['Exchange Proximity']}/100

Key Risk Flags:
${caseData.highRiskReasons.map(r => `* ${r}`).join('\n')}

3. CLUSTERED WALLET IDENTIFIERS
--------------------------------------------------------------------------------
Cluster Root: ${caseData.clusterData.root}
Associated Addresses: ${caseData.clusterData.relatedAddressesCount}
${caseData.clusterData.clusterEntities.map(e => `* [${e.correlationScore}% Correlation] ${e.alias}: ${e.address} (Reason: ${e.reason})`).join('\n')}

4. TRANSACTION FLOW TRACE
--------------------------------------------------------------------------------
${caseData.edges.map(edge => `Hop ${edge.hop}: [${edge.source}] ---> [${edge.target}] | ${edge.amount} (${edge.usdValue}) | TX: ${edge.txHash}`).join('\n')}

5. EXCHANGE ATTRIBUTION DETAILS
--------------------------------------------------------------------------------
Target Entity:    ${caseData.attribution.exchange}
Wallet Category:  ${caseData.attribution.walletType}
Deposit Cluster:  ${caseData.attribution.depositCluster || 'N/A'}
Jurisdiction:     ${caseData.attribution.jurisdiction || 'International'}
Confidence Score: ${caseData.attribution.confidence}%

Attribution Evidence:
${caseData.attribution.evidence.map(ev => `* ${ev}`).join('\n')}

DISCLAIMER:
${caseData.attribution.warning}
This simulated intelligence dossier is generated by TraceGuard for demonstrative and 
analytical testing only. No real financial institution was contacted or notified.
================================================================================
`;

    const blob = new Blob([textReport], { type: 'text/plain;charset=utf-8' });
    const url = URL.createObjectURL(blob);
    const link = document.createElement('a');
    link.href = url;
    link.download = `${reportReference}_Forensic_Dossier.txt`;
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
    URL.revokeObjectURL(url);
  };

  const handlePrint = () => {
    window.print();
  };

  return (
    <div
      className="fixed inset-0 z-50 bg-black/80 flex items-center justify-center p-4 sm:p-6 backdrop-blur-xs overflow-y-auto"
      role="dialog"
      aria-modal="true"
      aria-labelledby="report-modal-title"
    >
      <div className="bg-[#0D1721] border border-[#243443] rounded-xl max-w-4xl w-full max-h-[90vh] flex flex-col shadow-2xl animate-in fade-in zoom-in-95 duration-200">
        {/* Top Action Bar */}
        <div className="p-4 border-b border-[#243443] flex items-center justify-between bg-[#111F2C]">
          <div className="flex items-center gap-2.5">
            <FileText className="w-5 h-5 text-[#38BDF8]" />
            <div>
              <h2 id="report-modal-title" className="text-sm font-semibold text-white">Forensic Investigation Dossier</h2>
              <div className="text-[11px] font-mono-code text-[#8EA1B2]">REF: {reportReference}</div>
            </div>
          </div>

          <div className="flex items-center gap-2">
            <button
              onClick={handleCopyJson}
              className="px-2.5 py-1.5 rounded-lg bg-[#071018] border border-[#243443] hover:border-[#38BDF8] text-[#8EA1B2] hover:text-white text-xs font-mono-code flex items-center gap-1.5 transition-colors cursor-pointer"
              title="Copy JSON representation"
            >
              {copied ? <Check className="w-3.5 h-3.5 text-emerald-400" /> : <Copy className="w-3.5 h-3.5" />}
              <span>{copied ? 'Copied' : 'JSON'}</span>
            </button>
            <button
              onClick={handlePrint}
              className="px-2.5 py-1.5 rounded-lg bg-[#071018] border border-[#243443] hover:border-[#38BDF8] text-[#8EA1B2] hover:text-white text-xs font-mono-code flex items-center gap-1.5 transition-colors cursor-pointer"
              title="Print dossier"
            >
              <Printer className="w-3.5 h-3.5" />
              <span>Print</span>
            </button>
            <button
              onClick={handleDownloadReport}
              className="px-3 py-1.5 rounded-lg bg-[#38BDF8] hover:bg-[#0284C7] text-slate-950 text-xs font-semibold flex items-center gap-1.5 transition-colors cursor-pointer"
            >
              <Download className="w-3.5 h-3.5" />
              <span>Download Dossier</span>
            </button>
            <button
              onClick={onClose}
              className="text-[#8EA1B2] hover:text-white p-1.5 rounded-lg hover:bg-[#071018] transition-colors ml-1 cursor-pointer"
              aria-label="Close modal"
            >
              <X className="w-4 h-4" />
            </button>
          </div>
        </div>

        {/* Scrollable Report Document */}
        <div className="p-6 overflow-y-auto space-y-6 text-[#E7EEF5] text-xs font-sans">
          {/* Header Banner */}
          <div className="p-4 rounded-lg bg-[#071018] border border-[#243443] flex flex-col md:flex-row md:items-center justify-between gap-4">
            <div>
              <div className="flex items-center gap-2">
                <span className="text-base font-bold text-white tracking-tight">{caseData.title}</span>
                <RiskBadge level={caseData.severity} score={caseData.riskScore} size="sm" />
              </div>
              <div className="text-xs text-[#8EA1B2] mt-1 flex flex-wrap items-center gap-x-4 gap-y-1 font-mono-code">
                <span>CASE ID: <strong className="text-white">{caseData.id}</strong></span>
                <span>CHAIN: <strong className="text-[#38BDF8]">{caseData.blockchain}</strong></span>
                <span>ORIGIN: <strong className="text-white">{caseData.source}</strong></span>
                <span>TIMESTAMP: <strong className="text-[#8EA1B2]">{reportDate}</strong></span>
              </div>
            </div>
            <div className="text-right shrink-0">
              <div className="text-[10px] font-mono-code uppercase tracking-wider text-[#8EA1B2]">Potentially Traced Funds</div>
              <div className="text-xl font-bold font-mono-code text-white">${caseData.suspiciousAmount.toLocaleString()} USD</div>
            </div>
          </div>

          {/* Section 1: Executive Summary */}
          <div className="space-y-2">
            <h3 className="text-xs font-bold uppercase tracking-wider text-[#38BDF8] font-mono-code border-b border-[#243443] pb-1">
              1. Executive Forensic Summary
            </h3>
            <p className="text-[#8EA1B2] leading-relaxed text-xs">
              TraceGuard automated telemetry tracked {caseData.nodes.length} nodes and {caseData.edges.length} hops originating from suspect address{' '}
              <span className="font-mono-code text-white bg-[#111F2C] px-1.5 py-0.5 rounded border border-[#243443]">{caseData.seedDetails.address}</span>. 
              The target flow utilized intermediate clustering, peel chain transaction structuring, and privacy mechanisms before reaching destination exchange{' '}
              <strong className="text-white">{caseData.attribution.exchange}</strong> with an attribution confidence rating of <strong className="text-emerald-400">{caseData.attribution.confidence}%</strong>.
            </p>
          </div>

          {/* Section 2: Key Risk Indicators */}
          <div className="space-y-3">
            <h3 className="text-xs font-bold uppercase tracking-wider text-[#38BDF8] font-mono-code border-b border-[#243443] pb-1">
              2. Risk Analysis Matrix
            </h3>
            <div className="grid grid-cols-2 sm:grid-cols-3 gap-2.5 font-mono-code">
              {Object.entries(caseData.riskComponents).map(([name, score]) => (
                <div key={name} className="p-2.5 rounded-lg bg-[#071018] border border-[#243443]">
                  <div className="text-[10px] text-[#8EA1B2] truncate">{name}</div>
                  <div className="text-sm font-bold text-white mt-1 flex items-center justify-between">
                    <span>{score}/100</span>
                    <span className={`text-[10px] ${score > 70 ? 'text-red-400' : score > 40 ? 'text-amber-400' : 'text-emerald-400'}`}>
                      {score > 70 ? 'HIGH' : score > 40 ? 'ELEVATED' : 'NOMINAL'}
                    </span>
                  </div>
                </div>
              ))}
            </div>

            <div className="space-y-1.5 pt-1">
              <div className="text-[11px] font-semibold text-white">Specific Risk Triggers:</div>
              <ul className="space-y-1 text-xs text-[#8EA1B2]">
                {caseData.highRiskReasons.map((reason, idx) => (
                  <li key={idx} className="flex items-start gap-2">
                    <span className="text-red-400 font-bold">•</span>
                    <span>{reason}</span>
                  </li>
                ))}
              </ul>
            </div>

            {/* Plain-Language Threat Narrative */}
            <RiskExplanationBox
              riskScore={caseData.riskScore}
              severity={caseData.severity}
              riskComponents={caseData.riskComponents}
              highRiskReasons={caseData.highRiskReasons}
              attribution={caseData.attribution}
            />
          </div>

          {/* Section 3: Clustered Entities */}
          <div className="space-y-2">
            <h3 className="text-xs font-bold uppercase tracking-wider text-[#38BDF8] font-mono-code border-b border-[#243443] pb-1">
              3. Heuristic Address Cluster ({caseData.clusterData.relatedAddressesCount} Related Wallets)
            </h3>
            <div className="space-y-2">
              {caseData.clusterData.clusterEntities.map((entity, i) => (
                <div key={i} className="p-2.5 rounded-lg bg-[#071018] border border-[#243443] flex flex-col sm:flex-row sm:items-center justify-between gap-2 font-mono-code text-[11px]">
                  <div>
                    <div className="text-white font-semibold flex items-center gap-2">
                      <span>{entity.alias}</span>
                      <span className="text-[10px] px-1.5 py-0.2 rounded bg-[#38BDF8]/10 text-[#38BDF8] border border-[#38BDF8]/30">
                        {entity.correlationScore}% Correlation
                      </span>
                    </div>
                    <div className="text-[#8EA1B2] text-[10px] mt-0.5">{entity.address}</div>
                    <div className="text-[#8EA1B2] text-[10px] font-sans italic mt-0.5">{entity.reason}</div>
                  </div>
                  <div className="text-right text-xs text-white shrink-0">
                    <div>Balance: {entity.balance}</div>
                    <div className="text-[10px] text-[#8EA1B2]">Seen: {entity.firstSeen}</div>
                  </div>
                </div>
              ))}
            </div>
          </div>

          {/* Section 4: Exchange Attribution */}
          <div className="space-y-2">
            <h3 className="text-xs font-bold uppercase tracking-wider text-[#38BDF8] font-mono-code border-b border-[#243443] pb-1">
              4. Centralized Counterparty Attribution
            </h3>
            <div className="p-3 rounded-lg bg-[#071018] border border-[#243443] space-y-2">
              <div className="flex items-center justify-between flex-wrap gap-2">
                <div>
                  <div className="text-sm font-bold text-white">{caseData.attribution.exchange}</div>
                  <div className="text-[11px] text-[#8EA1B2] font-mono-code">{caseData.attribution.walletType}</div>
                </div>
                <div className="text-right">
                  <div className="text-xs font-mono-code text-emerald-400 font-bold">{caseData.attribution.confidence}% Confidence</div>
                  <div className="text-[10px] text-[#8EA1B2]">{caseData.attribution.jurisdiction || 'Global'}</div>
                </div>
              </div>
              <div className="text-xs text-[#8EA1B2] space-y-1 pt-1 border-t border-[#243443]/60">
                <div className="font-semibold text-white text-[11px]">Corroborating Telemetry:</div>
                {caseData.attribution.evidence.map((ev, i) => (
                  <div key={i} className="flex items-center gap-2 text-[11px]">
                    <span className="text-[#38BDF8] font-mono-code">✓</span>
                    <span>{ev}</span>
                  </div>
                ))}
              </div>
            </div>
          </div>

          {/* Legal / Prototype Disclaimer Box */}
          <div className="p-3 rounded-lg bg-amber-500/10 border border-amber-500/30 text-amber-200 text-xs flex items-start gap-2.5">
            <ShieldAlert className="w-4 h-4 shrink-0 text-amber-400 mt-0.5" />
            <div className="space-y-0.5">
              <div className="font-semibold text-amber-300">Demonstration Simulation Disclaimer</div>
              <p className="text-[11px] text-amber-200/80 leading-relaxed">
                This document is generated by the TraceGuard prototype using simulated blockchain heuristics. 
                Data points herein represent demonstrative mock records and are not real-world actionable evidence.
              </p>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
};
